[package]
name = "rocketviewer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"
bevy_egui = "0.39.1"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
serialport5 = "5.0.2"
